<?php
/** @var \SDN\TestPage\Block\Page\View $block */

$category = $block->getCurrentCategory();
$_category = $block->getCategory();
$hello = $block->test();
?>
<?php if ($category) : ?>
<?php $subcats = $category->getChildrenCategories(); ?>
<div>
    <ul>
        <?php foreach ($subcats as $subcat) : ?>
            <?php if ($subcat->getIsActive()) : ?>
                <?php $_category = $block->getCategory()->load($subcat->getId()); ?>
                <?php $subcaturl = $subcat->getUrl(); ?>
                <?php if ($_imgUrl = $_category->getImageUrl()) : ?>
                    <div>
                        <img style="width: 100%;" src="<?= $_imgUrl ?>" alt=""/>
                        <span> <a href="<?= $subcaturl ?>" class="block-promo"
                                  title="<?= $subcat->getName() ?>"></a><?= $subcat->getName() ?>
                        </span>
                    </div>
                <?php endif; ?>
            <?php endif; ?>
        <?php endforeach ?>
    </ul>
    <?php endif; ?>
    <H3>jkhjkjhkjhkjhQQQQQQQQQQQQ</H3>
    <H3><?= $hello ?></H3>
</div>
